"use client";

import { useMemo, useState } from "react";
import { weekdays } from "../../data/sampleTimetable";
import { normalizeBlockName, previewDayTemplateAssignment } from "../../lib/dayTimetableTemplates";
import { formatBlockTime, getBlocksForDay } from "../../lib/periodStructures";
import ModalDialog from "../classes/ModalDialog";
import { useSchoolData } from "../providers/SchoolDataProvider";
import styles from "./setup.module.css";

function TemplateForm({ templates, initial, onSave, onCancel }) {
  const [name, setName] = useState(initial?.name ?? "");
  const [sourceTemplateId, setSourceTemplateId] = useState(initial?.sourceTemplateId ?? "");
  const [errors, setErrors] = useState({});
  const [saving, setSaving] = useState(false);
  async function submit(event) { event.preventDefault(); if (saving) return; setSaving(true); const result = await onSave(name, sourceTemplateId); setSaving(false); if (!result.ok) setErrors(result.errors); }
  return <form className={styles.templateForm} onSubmit={submit} noValidate><h3>{initial?.mode === "rename" ? "Rename Template" : initial?.mode === "duplicate" ? "Duplicate Template" : "Add Template"}</h3><label>Template Name (required)<input autoFocus maxLength={80} value={name} aria-invalid={Boolean(errors.name)} onChange={(event) => setName(event.target.value)} />{errors.name && <span>{errors.name}</span>}</label>{initial?.mode === "create" && <label>Starting Structure<select value={sourceTemplateId} onChange={(event) => setSourceTemplateId(event.target.value)}><option value="">Start empty</option>{templates.map((template) => <option key={template.id} value={template.id}>Copy {template.name}</option>)}</select></label>}<div className={styles.formActions}><button type="button" className={styles.secondarySetupButton} onClick={onCancel} disabled={saving}>Cancel</button><button className={styles.primarySetupButton} disabled={saving}>{saving ? "Saving…" : "Save Template"}</button></div></form>;
}

function BlockForm({ initial, templateId, onSave, onCancel }) {
  const [values, setValues] = useState(initial ?? { templateId, name: "", startTime: "", endTime: "", isTeaching: true });
  const [errors, setErrors] = useState({});
  const [saving, setSaving] = useState(false);
  async function submit(event) { event.preventDefault(); if (saving) return; setSaving(true); const result = await onSave({ ...values, templateId }); setSaving(false); if (!result.ok) setErrors(result.errors); }
  return <form className={styles.blockForm} onSubmit={submit} noValidate><h3>{initial ? "Edit Block" : "Add Block"}</h3><label>Name (required)<input autoFocus maxLength={40} value={values.name} aria-invalid={Boolean(errors.name)} onChange={(event) => setValues({ ...values, name: event.target.value })} />{errors.name && <span>{errors.name}</span>}</label><div className={styles.timeFields}><label>Start Time (required)<input type="time" value={values.startTime} aria-invalid={Boolean(errors.startTime || errors.timeRange)} onChange={(event) => setValues({ ...values, startTime: event.target.value })} />{errors.startTime && <span>{errors.startTime}</span>}</label><label>End Time (required)<input type="time" value={values.endTime} aria-invalid={Boolean(errors.endTime || errors.timeRange)} onChange={(event) => setValues({ ...values, endTime: event.target.value })} />{errors.endTime && <span>{errors.endTime}</span>}</label></div>{errors.timeRange && <p className={styles.setupError}>{errors.timeRange}</p>}<fieldset><legend>Block Type</legend><div className={styles.typeSelector}>{[[true, "Teaching period"], [false, "Non-teaching block"]].map(([value, label]) => <button key={label} type="button" disabled={saving} aria-pressed={values.isTeaching === value} onClick={() => setValues({ ...values, isTeaching: value })}>{label}</button>)}</div></fieldset>{errors.form && <p className={styles.setupError} role="alert">{errors.form}</p>}<div className={styles.formActions}><button type="button" className={styles.secondarySetupButton} onClick={onCancel} disabled={saving}>Cancel</button><button className={styles.primarySetupButton} disabled={saving}>{saving ? "Saving…" : "Save Block"}</button></div></form>;
}

export default function PeriodStructureManager() {
  const data = useSchoolData();
  const { dayTimetableTemplates: templates, dayTimetableTemplateBlocks: templateBlocks, dayTimetableAssignments: assignments, timetableBlocks } = data;
  const [selectedId, setSelectedId] = useState(null);
  const [templateForm, setTemplateForm] = useState(null);
  const [blockForm, setBlockForm] = useState(null);
  const [deleteTarget, setDeleteTarget] = useState(null);
  const [removeBlock, setRemoveBlock] = useState(null);
  const [pendingAssignment, setPendingAssignment] = useState(null);
  const [bulkTemplateId, setBulkTemplateId] = useState("");
  const [message, setMessage] = useState("");
  const selectedTemplate = templates.find((template) => template.id === selectedId) ?? templates[0];
  const blocks = useMemo(() => templateBlocks.filter((block) => block.templateId === selectedTemplate?.id).sort((a, b) => a.displayOrder - b.displayOrder), [templateBlocks, selectedTemplate]);

  async function saveTemplate(name, sourceTemplateId) { const result = templateForm.mode === "rename" ? await data.renameDayTemplate(templateForm.id, name) : await data.createDayTemplate(name, sourceTemplateId || templateForm.sourceTemplateId); if (result.ok) setTemplateForm(null); return result; }
  async function saveBlock(values) { const result = await data.saveDayTemplateBlock({ ...blockForm, ...values }); if (result.ok) setBlockForm(null); return result; }
  async function confirmDelete() { const result = await data.deleteDayTemplate(deleteTarget.id); setMessage(result.ok ? "Template deleted." : result.message); setDeleteTarget(null); }
  async function confirmRemoveBlock() { const result = await data.removeDayTemplateBlock(removeBlock.id); setMessage(result.ok ? "Template block removed from every assigned day." : result.message); setRemoveBlock(null); }
  async function confirmAssignment() { const result = await data.assignDayTemplate(pendingAssignment.templateId, pendingAssignment.cycleWeek, pendingAssignment.weekday); setMessage(result.ok ? "Day template updated." : result.message); setPendingAssignment(null); }
  function requestAssignment(cycleWeek, weekday, templateId) {
    const current = getBlocksForDay(timetableBlocks, cycleWeek, weekday);
    const target = templateBlocks.filter((block) => block.templateId === templateId);
    const targetsByName = new Map(target.map((block) => [normalizeBlockName(block.name), block]));
    const blockers = [];
    for (const slot of current) {
      const destination = targetsByName.get(normalizeBlockName(slot.name));
      const classAssignment = [...data.recurringAssignments, ...data.historicalRecurringAssignments].find((item) => item.periodId === slot.id);
      const event = data.recurringEvents.find((item) => item.periodId === slot.id);
      const movement = data.lessonMovements.find((item) => item.destinationPeriodId === slot.id);
      const lesson = data.lessonOccurrences.find((item) => item.periodId === slot.id);
      const usage = classAssignment ? data.classes.find((item) => item.id === classAssignment.classId)?.shortCode ?? "Class" : event?.title ?? (movement ? "Dated lesson movement" : lesson ? "Saved lesson history" : "");
      if (!destination && usage) blockers.push(`${slot.name}: ${usage}`);
      else if (destination && !destination.isTeaching && (classAssignment || movement)) blockers.push(`${slot.name}: ${usage} requires a teaching block`);
    }
    setPendingAssignment({ cycleWeek, weekday, templateId, preview: previewDayTemplateAssignment(current, target), blockers });
  }
  async function applyToAllDays() { if (!bulkTemplateId) return; const days = ["A", "B"].flatMap((cycleWeek) => weekdays.map((weekday) => ({ cycleWeek, weekday: weekday.key }))); const result = await data.bulkAssignDayTemplate(bulkTemplateId, days); setMessage(result.ok ? "Template applied to all Week A and Week B weekdays." : result.message); }

  return <section className={styles.editorSection} aria-labelledby="day-timetables-title"><div className={styles.sectionHeading}><div><h2 id="day-timetables-title">Day Timetables</h2><p>Configure reusable day structures once, then assign them across Week A and Week B.</p></div><button className={styles.primarySetupButton} onClick={() => setTemplateForm({ mode: "create" })}>Add Template</button></div>{message && <p className={styles.setupMessage} role="status">{message}</p>}
    <div className={styles.templateWorkspace}><aside className={styles.templateList} aria-label="Day timetable templates">{templates.map((template) => { const count = assignments.filter((item) => item.templateId === template.id).length; const blockCount = templateBlocks.filter((item) => item.templateId === template.id).length; return <button key={template.id} type="button" aria-pressed={selectedTemplate?.id === template.id} onClick={() => { setSelectedId(template.id); setBlockForm(null); }}><strong>{template.name}</strong><span>{blockCount} {blockCount === 1 ? "block" : "blocks"} · Used by {count} {count === 1 ? "day" : "days"}</span></button>; })}</aside>
      <div className={styles.templateEditor}>{selectedTemplate ? <><div className={styles.structureHeading}><div><h3>{selectedTemplate.name}</h3><p>Changes update every assigned day.</p></div><div className={styles.templateActions}><button onClick={() => setTemplateForm({ mode: "rename", id: selectedTemplate.id, name: selectedTemplate.name })}>Rename</button><button onClick={() => setTemplateForm({ mode: "duplicate", sourceTemplateId: selectedTemplate.id, name: `${selectedTemplate.name} Copy` })}>Duplicate</button><button onClick={() => setDeleteTarget(selectedTemplate)}>Delete</button><button className={styles.primarySetupButton} onClick={() => setBlockForm({ templateId: selectedTemplate.id, name: "", startTime: "", endTime: "", isTeaching: true })}>Add Block</button></div></div>{blockForm && <BlockForm key={blockForm.id ?? "new-block"} initial={blockForm.id ? blockForm : null} templateId={selectedTemplate.id} onSave={saveBlock} onCancel={() => setBlockForm(null)} />}{blocks.length ? <div className={styles.blockList}>{blocks.map((block, index) => <article className={styles.blockRow} key={block.id}><span className={styles.orderNumber}>{index + 1}</span><div><strong>{block.name}</strong><span>{formatBlockTime(block.startTime)}–{formatBlockTime(block.endTime)}</span><small>{block.isTeaching ? "Teaching period" : "Non-teaching block"}</small></div><div className={styles.blockActions}><button aria-label={`Move ${block.name} up`} disabled={index === 0} onClick={() => data.moveDayTemplateBlock(block.id, -1)}>↑</button><button aria-label={`Move ${block.name} down`} disabled={index === blocks.length - 1} onClick={() => data.moveDayTemplateBlock(block.id, 1)}>↓</button><button onClick={() => setBlockForm(block)}>Edit</button><button onClick={() => setRemoveBlock(block)}>Remove</button></div></article>)}</div> : <div className={styles.emptyStructure}><p>This template has no blocks yet.</p></div>}</> : <div className={styles.emptyStructure}><p>Add your first reusable day template.</p></div>}</div>
    </div>
    <section className={styles.dayAssignments} aria-labelledby="day-assignments-title"><div className={styles.sectionHeading}><div><h3 id="day-assignments-title">Assign to Days</h3><p>Compatible block names keep their existing stable timetable slots and occupants.</p></div></div><div className={styles.assignmentWeeks}>{["A", "B"].map((cycleWeek) => <fieldset key={cycleWeek}><legend>Week {cycleWeek}</legend>{weekdays.map((weekday) => { const assignment = assignments.find((item) => item.cycleWeek === cycleWeek && item.weekday === weekday.key); return <label key={weekday.key}><span>{weekday.label}</span><select aria-label={`Week ${cycleWeek} ${weekday.label} template`} value={assignment?.templateId ?? ""} onChange={(event) => requestAssignment(cycleWeek, weekday.key, event.target.value)}><option value="" disabled>Choose template</option>{templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select></label>; })}</fieldset>)}</div><div className={styles.bulkAssignment}><label>Quick apply<select value={bulkTemplateId} onChange={(event) => setBulkTemplateId(event.target.value)}><option value="">Choose template</option>{templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select></label><button className={styles.secondarySetupButton} disabled={!bulkTemplateId} onClick={applyToAllDays}>Apply to all Week A/B weekdays</button></div></section>
    {templateForm && <ModalDialog className={styles.blockConfirmDialog} labelledBy="template-form-title" onClose={() => setTemplateForm(null)}><div id="template-form-title"><TemplateForm templates={templates} initial={templateForm} onSave={saveTemplate} onCancel={() => setTemplateForm(null)} /></div></ModalDialog>}
    {deleteTarget && <ModalDialog className={styles.blockConfirmDialog} labelledBy="delete-template-title" onClose={() => setDeleteTarget(null)}><h2 id="delete-template-title">Delete {deleteTarget.name}?</h2><p>Only unused templates can be deleted. No days will be reassigned automatically.</p><div className={styles.formActions}><button className={styles.secondarySetupButton} onClick={() => setDeleteTarget(null)}>Cancel</button><button className={styles.dangerSetupButton} onClick={confirmDelete}>Delete Template</button></div></ModalDialog>}
    {removeBlock && <ModalDialog className={styles.blockConfirmDialog} labelledBy="remove-template-block-title" onClose={() => setRemoveBlock(null)}><h2 id="remove-template-block-title">Remove {removeBlock.name}?</h2><p>This removes the corresponding empty slot from every assigned day. Occupied or referenced slots block removal.</p><div className={styles.formActions}><button className={styles.secondarySetupButton} onClick={() => setRemoveBlock(null)}>Cancel</button><button className={styles.dangerSetupButton} onClick={confirmRemoveBlock}>Remove Block</button></div></ModalDialog>}
    {pendingAssignment && <ModalDialog className={styles.blockConfirmDialog} labelledBy="assign-template-title" onClose={() => setPendingAssignment(null)}><h2 id="assign-template-title">{pendingAssignment.blockers.length ? "Cannot apply" : "Apply"} {templates.find((item) => item.id === pendingAssignment.templateId)?.name}{pendingAssignment.blockers.length ? "" : "?"}</h2><p>Week {pendingAssignment.cycleWeek} · {weekdays.find((item) => item.key === pendingAssignment.weekday)?.label}</p><div className={styles.assignmentPreview}><p><strong>Preserved:</strong> {pendingAssignment.preview.preserved.join(", ") || "None"}</p><p><strong>Added:</strong> {pendingAssignment.preview.added.join(", ") || "None"}</p><p><strong>Removed if empty:</strong> {pendingAssignment.preview.removed.join(", ") || "None"}</p>{pendingAssignment.blockers.length > 0 && <><strong>Resolve first:</strong><ul>{pendingAssignment.blockers.map((blocker) => <li key={blocker}>{blocker}</li>)}</ul></>}</div><div className={styles.formActions}><button className={styles.secondarySetupButton} onClick={() => setPendingAssignment(null)}>{pendingAssignment.blockers.length ? "Close" : "Cancel"}</button>{pendingAssignment.blockers.length === 0 && <button className={styles.primarySetupButton} onClick={confirmAssignment}>Apply Template</button>}</div></ModalDialog>}
  </section>;
}
